## milvus.yaml
#version: 2.4
#dataCoord:
#  enableCompaction: true
#
#storage:
#  path: /var/lib/milvus
#
#log:
#  level: info
#
#common:
#  security:
#    authorizationEnabled: false
#
#etcd:
#  endpoints:
#    - etcd:2379
#
#minio:
#  address: minio:9000
#  accessKeyID: luke
#  secretAccessKey: luke_password
#  bucketName: milvus-bucket
# milvus.yaml for standalone mode

version: 2.4

storage:
  path: /var/lib/milvus

log:
  level: info

etcd:
  endpoints:
    - etcd:2379

minio:
  address: minio:9000
  accessKeyID: luke
  secretAccessKey: password
  bucketName: milvus-bucket

common:
  security:
    authorizationEnabled: false
