version: "0.1"

services:
  postgres:
    build: ./postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/config:/docker-entrypoint-initdb.d
    networks:
      - development

  neo4j:
    build: ./neo4j
    container_name: ${NEO4J_CONTAINER_NAME}
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./neo4j/config:/config
      - ./neo4j/plugins:/plugins
      - ./neo4j/logs:/logs
    restart: always
    networks:
      - development

  milvus:
    build: ./milvus
    container_name: ${MILVUS_CONTAINER_NAME}
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
      - ./milvus/config:/milvus/configs
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    depends_on:
      - etcd
      - minio
    networks:
      - development

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd-data
    command:
      - etcd
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://127.0.0.1:2379
      - --listen-client-urls=http://0.0.0.0:2379
    networks:
      - development

  minio:
    image: minio/minio:latest
    container_name: ${MINIO_CONTAINER_NAME}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data
    networks:
      - development


volumes:
  pgdata:
  neo4j_data:
  milvus_data:
  minio_data:
  etcd_data:

networks:
  development:
    driver: bridge
